// Generated by scripts/bake-rerolls.ts. Do not edit by hand.
// Endless levels whose first build repeats an earlier maze, and the reroll
// that makes them new (checked for every level up to REROLLS_CHECKED).
export const REROLLS_CHECKED = 0;
export const REROLLS: Record<number, number> = {};
