// Plays through the endless levels in order, as a player would, and writes
// down every level whose first build repeats an earlier maze (turned or
// mirrored counts) together with the reroll that makes it new. The game
// then uses those rerolls directly, so no player ever meets a repeat.
//
// Usage: node --experimental-strip-types scripts/bake-rerolls.ts [levels]
import { writeFileSync } from 'node:fs';
import { getLevel, rerolled } from '../src/levels/list.ts';
import { REROLLS } from '../src/levels/rerolls.ts';

const N = Number(process.argv[2] ?? 3000);
const t0 = Date.now();
for (let n = 1; n <= N; n++) {
  getLevel(n);
  if (n % 100 === 0) console.log(`${n} levels, ${rerolled.size} rerolled, ${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
const all = { ...REROLLS };
for (const [n, r] of rerolled) all[n] = r;
const body = Object.entries(all)
  .sort((a, b) => Number(a[0]) - Number(b[0]))
  .map(([n, r]) => `  ${n}: ${r},`)
  .join('\n');
writeFileSync(
  new URL('../src/levels/rerolls.ts', import.meta.url),
  `// Generated by scripts/bake-rerolls.ts. Do not edit by hand.
// Endless levels whose first build repeats an earlier maze, and the reroll
// that makes them new (checked for every level up to REROLLS_CHECKED).
export const REROLLS_CHECKED = ${N};
export const REROLLS: Record<number, number> = {
${body}
};
`,
);
console.log(`done: ${N} levels, rerolls at ${Object.keys(all).join(', ') || 'none'}`);
