// Builds the curated level set at full search effort and writes
// src/levels/data.ts. Levels after these are built in the game itself by
// the same builder (src/levels/builder.ts), so the game never runs out.
//
// Usage: node --experimental-strip-types scripts/build-levels.ts [count]
import { writeFileSync } from 'node:fs';
import { buildLevel, encodeLevel, FIRST_BUILT } from '../src/levels/builder.ts';

const count = Number(process.argv[2] ?? 200);
const out: string[] = [];
const t0 = Date.now();
for (let n = FIRST_BUILT; n <= count; n++) {
  const { c, bonus } = buildLevel(n, 1);
  out.push(encodeLevel(c, bonus));
  const tiles = c.grid.flat().filter((v) => v !== 1).length;
  console.error(`${n} ${c.name} ${c.grid[0].length}x${c.grid.length} tiles=${tiles} par=${c.par} ${Date.now() - t0}ms`);
}

const body = `// Generated by scripts/build-levels.ts. Do not edit by hand.
// name|bonus|par|rows (see parseLevel in core.ts for the characters)
export const LEVEL_DATA_FIRST = ${FIRST_BUILT};
export const LEVEL_DATA: string[] = ${JSON.stringify(out, null, 0).replace(/","/g, '",\n  "').replace('["', '[\n  "').replace('"]', '",\n]')};
`;
writeFileSync(new URL('../src/levels/data.ts', import.meta.url), body);
console.error(`wrote ${out.length} levels`);
